# Generated by Django 3.2.9 on 2021-12-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('day', models.TextField(max_length=500)),
                ('reminder', models.BooleanField(default=False)),
            ],
        ),
    ]
